// <auto-generated />
using System;
using CS.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CS.EF.Migrations
{
    [DbContext(typeof(CadSysContext))]
    partial class CadSysContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CS.Data.Entities.ActProprietate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Carnet");

                    b.Property<DateTime>("Data");

                    b.Property<string>("Emitent");

                    b.Property<int>("ExcelRow");

                    b.Property<int>("Index");

                    b.Property<string>("Numar")
                        .IsRequired();

                    b.Property<decimal>("Suprafata");

                    b.Property<int>("TipActProprietateId");

                    b.HasKey("Id");

                    b.HasIndex("TipActProprietateId");

                    b.ToTable("ActeProprietate");
                });

            modelBuilder.Entity("CS.Data.Entities.Dictionaries.UAT", b =>
                {
                    b.Property<int>("Id");

                    b.Property<string>("Denumire")
                        .IsRequired();

                    b.Property<int>("JudetId");

                    b.HasKey("Id");

                    b.HasIndex("JudetId");

                    b.ToTable("UAT");

                    b.HasData(
                        new { Id = 1, Denumire = "Sarateni", JudetId = 1 }
                    );
                });

            modelBuilder.Entity("CS.Data.Entities.Inscriere", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ExcelRow");

                    b.Property<int>("IdActProprietate");

                    b.Property<int>("IdParcela");

                    b.Property<int>("IdProprietar");

                    b.Property<int>("Index");

                    b.HasKey("Id");

                    b.HasIndex("IdActProprietate");

                    b.HasIndex("IdParcela");

                    b.HasIndex("IdProprietar");

                    b.ToTable("Inscrieri");
                });

            modelBuilder.Entity("CS.Data.Entities.Judet", b =>
                {
                    b.Property<int>("Id");

                    b.Property<string>("Denumire")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Judet");

                    b.HasData(
                        new { Id = 1, Denumire = "Ialomita" }
                    );
                });

            modelBuilder.Entity("CS.Data.Entities.Localitate", b =>
                {
                    b.Property<int>("Id");

                    b.Property<string>("Denumire")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Localitate");

                    b.HasData(
                        new { Id = 1, Denumire = "Sarateni" }
                    );
                });

            modelBuilder.Entity("CS.Data.Entities.Parcela", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CatFol");

                    b.Property<string>("Denumire")
                        .IsRequired();

                    b.Property<int>("ExcelRow");

                    b.Property<int>("Index");

                    b.Property<decimal>("Suprafata");

                    b.Property<int>("TarlaId");

                    b.Property<int?>("TarlaId1");

                    b.HasKey("Id");

                    b.HasIndex("TarlaId");

                    b.HasIndex("TarlaId1");

                    b.ToTable("Parcele");
                });

            modelBuilder.Entity("CS.Data.Entities.Proprietar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Adresa");

                    b.Property<string>("Emitent");

                    b.Property<int>("ExcelRow");

                    b.Property<long>("Identificator");

                    b.Property<int>("Index");

                    b.Property<string>("Initiala");

                    b.Property<string>("Judet");

                    b.Property<string>("Localitate");

                    b.Property<long>("Numar");

                    b.Property<string>("Nume");

                    b.Property<string>("Prenume");

                    b.Property<string>("Serie");

                    b.Property<int?>("Sex");

                    b.Property<string>("Tara");

                    b.Property<int?>("TipActIdentitate");

                    b.Property<int?>("TipPersoana");

                    b.HasKey("Id");

                    b.ToTable("Proprietari");
                });

            modelBuilder.Entity("CS.Data.Entities.Tara", b =>
                {
                    b.Property<int>("Id");

                    b.Property<string>("Denumire")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Tara");
                });

            modelBuilder.Entity("CS.Data.Entities.Tarla", b =>
                {
                    b.Property<int>("Id");

                    b.Property<string>("Denumire")
                        .IsRequired();

                    b.Property<int>("UATId");

                    b.HasKey("Id");

                    b.HasIndex("UATId");

                    b.ToTable("Tarlale");

                    b.HasData(
                        new { Id = 1, Denumire = "100", UATId = 1 },
                        new { Id = 2, Denumire = "102,1", UATId = 1 },
                        new { Id = 3, Denumire = "102,2", UATId = 1 },
                        new { Id = 4, Denumire = "104", UATId = 1 },
                        new { Id = 5, Denumire = "104,1", UATId = 1 },
                        new { Id = 6, Denumire = "104,2", UATId = 1 },
                        new { Id = 7, Denumire = "105,2", UATId = 1 },
                        new { Id = 8, Denumire = "105,3", UATId = 1 },
                        new { Id = 9, Denumire = "105,6", UATId = 1 },
                        new { Id = 10, Denumire = "110", UATId = 1 },
                        new { Id = 11, Denumire = "112,1", UATId = 1 },
                        new { Id = 12, Denumire = "112,2", UATId = 1 },
                        new { Id = 13, Denumire = "112,3", UATId = 1 },
                        new { Id = 14, Denumire = "114,1", UATId = 1 },
                        new { Id = 15, Denumire = "114,2", UATId = 1 },
                        new { Id = 16, Denumire = "117", UATId = 1 },
                        new { Id = 17, Denumire = "119,1", UATId = 1 },
                        new { Id = 18, Denumire = "119,2", UATId = 1 },
                        new { Id = 19, Denumire = "119,3", UATId = 1 },
                        new { Id = 20, Denumire = "119,4", UATId = 1 },
                        new { Id = 21, Denumire = "119,5", UATId = 1 },
                        new { Id = 22, Denumire = "129", UATId = 1 },
                        new { Id = 23, Denumire = "133,1", UATId = 1 },
                        new { Id = 24, Denumire = "133,2", UATId = 1 },
                        new { Id = 25, Denumire = "134,1", UATId = 1 },
                        new { Id = 26, Denumire = "134,2", UATId = 1 },
                        new { Id = 27, Denumire = "134,3", UATId = 1 },
                        new { Id = 28, Denumire = "136,2", UATId = 1 },
                        new { Id = 29, Denumire = "140", UATId = 1 },
                        new { Id = 30, Denumire = "140,4", UATId = 1 },
                        new { Id = 31, Denumire = "160,1", UATId = 1 },
                        new { Id = 32, Denumire = "161,1", UATId = 1 },
                        new { Id = 33, Denumire = "161,3", UATId = 1 },
                        new { Id = 34, Denumire = "161,4", UATId = 1 },
                        new { Id = 35, Denumire = "161,5", UATId = 1 },
                        new { Id = 36, Denumire = "161,6", UATId = 1 },
                        new { Id = 37, Denumire = "162,2", UATId = 1 },
                        new { Id = 38, Denumire = "162,4", UATId = 1 },
                        new { Id = 39, Denumire = "169,1", UATId = 1 },
                        new { Id = 40, Denumire = "177,1", UATId = 1 },
                        new { Id = 41, Denumire = "179,1", UATId = 1 },
                        new { Id = 42, Denumire = "179,2", UATId = 1 },
                        new { Id = 43, Denumire = "2420", UATId = 1 },
                        new { Id = 44, Denumire = "263,2", UATId = 1 },
                        new { Id = 45, Denumire = "267,4", UATId = 1 },
                        new { Id = 46, Denumire = "267,6", UATId = 1 },
                        new { Id = 47, Denumire = "267.1.6", UATId = 1 },
                        new { Id = 48, Denumire = "267.3.4", UATId = 1 },
                        new { Id = 49, Denumire = "276,6", UATId = 1 },
                        new { Id = 50, Denumire = "291.1.2", UATId = 1 },
                        new { Id = 51, Denumire = "297,1,2", UATId = 1 },
                        new { Id = 52, Denumire = "297,1,6", UATId = 1 },
                        new { Id = 53, Denumire = "297.1.2", UATId = 1 },
                        new { Id = 54, Denumire = "297.1.5", UATId = 1 },
                        new { Id = 55, Denumire = "297.1.6", UATId = 1 },
                        new { Id = 56, Denumire = "303,2", UATId = 1 },
                        new { Id = 57, Denumire = "303,6", UATId = 1 },
                        new { Id = 58, Denumire = "304,2", UATId = 1 },
                        new { Id = 59, Denumire = "329", UATId = 1 },
                        new { Id = 60, Denumire = "339,1", UATId = 1 },
                        new { Id = 61, Denumire = "341", UATId = 1 },
                        new { Id = 62, Denumire = "341,2", UATId = 1 },
                        new { Id = 63, Denumire = "345,1", UATId = 1 },
                        new { Id = 64, Denumire = "367,6", UATId = 1 },
                        new { Id = 65, Denumire = "383,1", UATId = 1 },
                        new { Id = 66, Denumire = "383,2", UATId = 1 },
                        new { Id = 67, Denumire = "383,3", UATId = 1 },
                        new { Id = 68, Denumire = "383,5", UATId = 1 },
                        new { Id = 69, Denumire = "393,1", UATId = 1 },
                        new { Id = 70, Denumire = "393,2", UATId = 1 },
                        new { Id = 71, Denumire = "393,3", UATId = 1 },
                        new { Id = 72, Denumire = "420,1", UATId = 1 },
                        new { Id = 73, Denumire = "420,2", UATId = 1 },
                        new { Id = 74, Denumire = "420,4", UATId = 1 },
                        new { Id = 75, Denumire = "422,1", UATId = 1 },
                        new { Id = 76, Denumire = "422,4", UATId = 1 },
                        new { Id = 77, Denumire = "422,6", UATId = 1 },
                        new { Id = 78, Denumire = "445", UATId = 1 },
                        new { Id = 79, Denumire = "445,1", UATId = 1 },
                        new { Id = 80, Denumire = "445,2", UATId = 1 },
                        new { Id = 81, Denumire = "471,2", UATId = 1 },
                        new { Id = 82, Denumire = "474,1", UATId = 1 },
                        new { Id = 83, Denumire = "474,2", UATId = 1 },
                        new { Id = 84, Denumire = "479,1", UATId = 1 },
                        new { Id = 85, Denumire = "479,2", UATId = 1 },
                        new { Id = 86, Denumire = "479,3", UATId = 1 },
                        new { Id = 87, Denumire = "479,5", UATId = 1 },
                        new { Id = 88, Denumire = "480,1", UATId = 1 },
                        new { Id = 89, Denumire = "480,4", UATId = 1 },
                        new { Id = 90, Denumire = "483,4", UATId = 1 },
                        new { Id = 91, Denumire = "483,5", UATId = 1 },
                        new { Id = 92, Denumire = "483,6", UATId = 1 },
                        new { Id = 93, Denumire = "483,8", UATId = 1 },
                        new { Id = 94, Denumire = "499,1", UATId = 1 },
                        new { Id = 95, Denumire = "51,5", UATId = 1 },
                        new { Id = 96, Denumire = "51,6", UATId = 1 },
                        new { Id = 97, Denumire = "51,7", UATId = 1 },
                        new { Id = 98, Denumire = "520,1", UATId = 1 },
                        new { Id = 99, Denumire = "520,4", UATId = 1 },
                        new { Id = 100, Denumire = "56,7", UATId = 1 },
                        new { Id = 101, Denumire = "64", UATId = 1 },
                        new { Id = 102, Denumire = "72,1", UATId = 1 },
                        new { Id = 103, Denumire = "72,2", UATId = 1 },
                        new { Id = 104, Denumire = "72,3", UATId = 1 },
                        new { Id = 105, Denumire = "72,4", UATId = 1 },
                        new { Id = 106, Denumire = "75,1", UATId = 1 },
                        new { Id = 107, Denumire = "76,1", UATId = 1 },
                        new { Id = 108, Denumire = "76,2", UATId = 1 },
                        new { Id = 109, Denumire = "79", UATId = 1 },
                        new { Id = 110, Denumire = "82,2", UATId = 1 },
                        new { Id = 111, Denumire = "94,1", UATId = 1 }
                    );
                });

            modelBuilder.Entity("CS.Data.Entities.TipActProprietate", b =>
                {
                    b.Property<int>("Id");

                    b.Property<string>("Denumire")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("TipuriActProprietate");

                    b.HasData(
                        new { Id = 1, Denumire = "Titlu Proptietate" },
                        new { Id = 2, Denumire = "Contract de Vanzare Cumparare" },
                        new { Id = 3, Denumire = "Sentinta Civila" },
                        new { Id = 4, Denumire = "Certificat de Mostenitor" },
                        new { Id = 5, Denumire = "Contract de Donatie" },
                        new { Id = 6, Denumire = "Contract de Vanzare Cumparare cu Clauza de Intretinere" },
                        new { Id = 7, Denumire = "Contract de Partaj Voluntar" },
                        new { Id = 8, Denumire = "Act de Partaj Voluntar" },
                        new { Id = 9, Denumire = "Contract de Partaj Imobiliar" },
                        new { Id = 10, Denumire = "Act de Donatie" }
                    );
                });

            modelBuilder.Entity("CS.Data.Entities.ActProprietate", b =>
                {
                    b.HasOne("CS.Data.Entities.TipActProprietate", "TipActProprietate")
                        .WithMany("ActeProprietate")
                        .HasForeignKey("TipActProprietateId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CS.Data.Entities.Dictionaries.UAT", b =>
                {
                    b.HasOne("CS.Data.Entities.Judet", "Judet")
                        .WithMany()
                        .HasForeignKey("JudetId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CS.Data.Entities.Inscriere", b =>
                {
                    b.HasOne("CS.Data.Entities.ActProprietate", "ActProprietate")
                        .WithMany("Inscrieri")
                        .HasForeignKey("IdActProprietate")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CS.Data.Entities.Parcela", "Parcela")
                        .WithMany("Inscrieri")
                        .HasForeignKey("IdParcela")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CS.Data.Entities.Proprietar", "Proprietar")
                        .WithMany("Inscrieri")
                        .HasForeignKey("IdProprietar")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CS.Data.Entities.Parcela", b =>
                {
                    b.HasOne("CS.Data.Entities.Tara", "Tarla")
                        .WithMany()
                        .HasForeignKey("TarlaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CS.Data.Entities.Tarla")
                        .WithMany("Parcele")
                        .HasForeignKey("TarlaId1");
                });

            modelBuilder.Entity("CS.Data.Entities.Tarla", b =>
                {
                    b.HasOne("CS.Data.Entities.Dictionaries.UAT", "UAT")
                        .WithMany()
                        .HasForeignKey("UATId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
